### PR TITLE
feat: OPX-3.2.0

### PR DESCRIPTION
**Pull request by Tejaswi-Goel**
Signed-off-by: Tejaswi Goel <Tejaswi_Goel@Dell.com>

### CODE REVIEW

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now e86fd0dd74a794d5b6d1842030e036cbac4b3f24

**Review by rakeshdatta — APPROVED** [review]

**Review by rakeshdatta — DISMISSED** [review]

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now db028fb04e69ca337d0f553d3e81b6f38f92fa11

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 36e9b539b876b3baca30306e885cea40e96181a5

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 79f78368c5d3caebea8b58f2f259beb24d29608f

**Review by pmithil7 — APPROVED** [review]

**Pull request merged**
